### PR TITLE
Handling case where user page is deleted

### LINKED ISSUE #9: Bug: When user page is deleted but user meta that user has a page is not.
This issue occurs under the following scenario:

1. User pages plugin is deactivated and/or unistalled 
2. User deletes the pages previously created for users.
3. User re-installs User Pages and activates plugin.
4. In the plugin admin user selects memberships levels that should have user pagesd and selects checkbox to create user pages for existing members.
5. Creation of user pages fails.

The cause of this issue is that the function checks whether the usermeta meta_key for pmproup_user_page exist but not whether the meta_value correlates with an existing post_id.

### PR DESCRIPTION
**Pull request by dparker1005**
Resolves #9

### CODE REVIEW

File: pmpro-user-pages.php [hunk 1]
```diff
@@ -310,6 +300,34 @@ function pmproup_pre_get_posts($query)
 }
 add_filter("pre_get_posts", "pmproup_pre_get_posts");
 
+/**
+ * Get the post_id for a user's page.
+ *
+ * @since 1.0
```
Comment (dparker1005) [inline pmpro-user-pages.php:306]:
```suggestion
 * @since TBD

```
